<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>php</string>
	</array>
	<key>name</key>
	<string>PHP - Doctrine Entity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.php</string>
			<key>name</key>
			<string>source.php.doctrine.entity.include.php</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.php.doctrine.entity</string>
	<key>uuid</key>
	<string>365d68a7-6779-4b57-950a-23c75ededc99</string>
</dict>
</plist>
